version: '3.8'

services:
  # incident-api:
  #   image: rogercc28/incident-api:6cb64e55defe95e497849205972f504086d17a86
  #   container_name: incident_api
  #   ports:
  #     - "3000:3000"
  #   environment: 
  #     MONGO_URL: mongodb://root:example@mongo
  #     PORT: 3000
  #   depends_on:
  #     - mongo


  mongo: 
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:
